### ISSUE TITLE
How to: assign predefined value (increm.refresh)

### ISSUE THREAD

**Issue by elsdestickere** [TabularEditor/Scripts#21]
Hi,

I'm trying to script the instructions on incremental refresh (https://docs.tabulareditor.com/te2/incremental-refresh.html).
I'm **stuck when I want to assign the value Month from the dropdown in IncrementalGranularity**.

This works:
var tableIncremNaam="facttable";
var tableIncrem = Model.Tables[tableIncremNaam];
tableIncrem.EnableRefreshPolicy = true;

This doesn't work: 
tableIncrem.IncrementalGranularity = tableIncrem.IncrementalGranularity.Month;
The error says: "use a typename for qualification", but I have no idea where to look. Any ideas?

Br Els

**Comment by otykier** [comment]
We generally use the same types as those defined in the [AMO/TOM client library](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.refreshgranularitytype?view=analysisservices-dotnet).

So in your case, to set the [IncrementalGranularity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.basicrefreshpolicy.incrementalgranularity?view=analysisservices-dotnet) use this code:

```csharp
 tableIncrem.IncrementalGranularity = RefreshGranularityType.Month;
```

**Comment by elsdestickere** [comment]
Super! Thanks @otykier 
I was looking in https://docs.microsoft.com/en-us/analysis-services/tom/introduction-to-the-tabular-object-model-tom-in-analysis-services-amo?view=asallproducts-allversions ... 1 step away
