### ISSUE TITLE
Summarize By property

### ISSUE THREAD

**Issue by rvgfox** [TabularEditor/Scripts#22]
Hi,

I'm trying to setup the value to the property "Summarize By" in an advanced script, but I don't know the sintax:

foreach(var c in Selected.Columns)
{
c.SummarizeBy = "none";  // Something it's wrong ??????
}

Thanks in advance

Ramon.

**Comment by dgosbell** [comment]
The SummarizeBy property is not a string property (see https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.column.summarizeby?view=analysisservices-dotnet) it expects an AggregateFunction enum value. So I think you will find that something like the following might work (I have not tested this)

```
foreach(var c in Selected.Columns)
{
c.SummarizeBy = AggregateFunction.None; 
}
```

**Comment by rvgfox** [comment]
> The SummarizeBy property is not a string property (see https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.column.summarizeby?view=analysisservices-dotnet) it expects an AggregateFunction enum value. So I think you will find that something like the following might work (I have not tested this)
> 
> ```
> foreach(var c in Selected.Columns)
> {
> c.SummarizeBy = AggregateFunction.None; 
> }
> ```

It works.  Thanks
