### ISSUE TITLE
Script to sync partitions with prod

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/Scripts#24]
Hi Scripties!
Imagine the following scenario:
You have a local dev-environment and a production environment with a huge data model. The production-data is being loaded through a integrated job environment and is scheduled automatically after refreshes in the Mart-Layer. 
The data amount of data is quite large and users want several refreshes per day to get fresh data, so we use partitions based on days as hot partitions and cold partitions based on months.
Each day  - on production - the job changes the partition interval and in case of a beginning of a new month is also creating a monthly partition.
This all happens automatically. The problem is, that the local dev environment does not receive these updates. My plan is now sync the partitions from prod to dev by using scripts.

I would like to create two scripts:

1) On a table - level I want to select the table and sync all partitions of the selected table with the prod-version
2) On a model level I would like to able to sync all partitions of the entire model

My C#-abilities however are not sufficient to solve this problem. I would like to ask for a little bit of help. My plan is:

1) I am sure, that all table names I want to sync are the same on Prod and Dev
2) I want to reach out to the prod server (how?) and save the partition-objects to the local Model (i could probably do that)
3) I want to create macros to start the script (I know how to do that)

I hope someone out there has got a similar problem (e.g. with Power-BI automatic aggregations?) and we can share our road to reaching that little snippet-goal :-)

Best regards,
Konstantin

**Comment by dgosbell** [comment]
Have you seen ALM Toolkit? http://alm-toolkit.com/ that tool is specifically targeted at comparing models and then synchronizing them.
