### ISSUE TITLE
Adding Clean Object Names script

### ISSUE THREAD

**Issue by markendicott** [TabularEditor/Scripts#4]
Hi Darren, 

As requested, see attached pbit file. 

Script is not cleaning up column or table names in lower_case_underscore format. Have tried setting this up as a custom action in Tabular Editor v 2.11.6, using the new External tools integration with Power BI. Data source is impala. When setting up as custom action, have tried saving this at just the Model level, and at the lower levels too, excluding those which it would not need to be ticked for any way. 

Any help would be appreciated!

Thanks, 
Mark
[cdm_mozaic_dataset.zip](https://github.com/TabularEditor/Scripts/files/4946587/cdm_mozaic_dataset.zip)

**Comment by dgosbell** [comment]
> using the new External tools integration with Power BI

So what appears to be happening is that Tabular Editor is blocking unsupported actions like renaming tables and columns when you are connected to a Power BI file (if you are connected to a SSAS database or .bim file the script works fine)

Currently only editing Measures, Calculation Groups and Perspectives is supported see [https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools)

If you go into the options for Tabular Editor and turn on the experimental feature support for Power BI the rename will work, but you should be very careful and take backups of your file when using this option as it could corrupt your model. Hopefully in the coming months Microsoft will be adding more features like renaming columns and tables to the supported actions

![image](https://user-images.githubusercontent.com/8241830/87995822-dd03b600-cb33-11ea-897a-1bc8393890cb.png)

**Comment by markendicott** [comment]
@dgosbell - Thank you very much for the additional information and help with this! 

Very much appreciated.

Mark
