### ISSUE TITLE
CreateExplicitMeasures_Blacklist

### ISSUE THREAD

**Issue by tomatminceddata** [TabularEditor/Scripts#9]
Creating explicit measures automatically is helpful, as they can be used with Calculation Groups, the new superpower of DAX in Power BI.
But, (as always) measures will clutter the field list no matter if they are moved to display folders or not. Even if it's faster to delete a measure in PBI Desktop than creating a simple measure (name, aggregate function, column reference), it's much more smarter to avoid the creation if one knows that the measure will not be needed.
Thus, I'm considering utilizing a blacklist, this list will contain information on tables and columns that will prevent measure creation.
I'm currently thinking about a very simple list (a tsv file for example, simply called MeasureBlackList.tsv).
A simple entry could look like

- tablename.*

The entry above will prevent the creation of any column inside the table tablename.
Other entries could look like this

- calendar.year
- calendar.month

Both entries above will avoid creating measures for the columns year and month in the table calendar.
I'm wondering about reasons that will prevent measure creation, what are your thoughts.

**Comment by otykier** [comment]
How about basing the script off of the `Selected.Columns` instead of `Model.AllColumns`, so that only selected columns or columns within the selected tables at the time of script execution are used for automatic measure creation?

**Comment by tomatminceddata** [comment]
Hmm, I'm a little hesitant, as I wanted to create the script as "runoften", whereas I consider Selected. ... as "runonce", as it can become difficult to make the same selection twice (of course this is depending on the time of the day).

But this reminds me that the measure has to be moved to its display folder once again if the measure is recreated after deletion.

**Comment by dgosbell** [comment]
For columns like Calendar Year and Calendar Month, wouldn't you just have the columns set to "Do not summarize" (in TE this would be AggregateFunction.None)? And shouldn't that block the creation of explicit measures anyway?

**Comment by tomatminceddata** [comment]
Hey Darren, 
the AggregateFunction.None will block measure creatiion.
I guess my example of these columns have been misleading, but I have to admit that I have no better example.

**Comment by dgosbell** [comment]
Yes, all the examples I can think of are things that I would mark as AggregateFunction.None anyway. Key columns and OrderBy columns are some other examples.

But if there were other circumstances the other possibility would be to do something like add a custom annotation. That way the script could be generic and data driven and would not require editing of a custom blacklist for different models.

**Comment by tomatminceddata** [comment]
Hey Darren, using custom annotation is brilliant. Thanks for the idea.

**Comment by dgosbell** [comment]
You could even possibly build a "run-once" style helper script that  would take the selected columns and build such an annotation(s) for you.

**Comment by tomatminceddata** [comment]
Hey @otykier , hey @dgosbell ,

I will close this issue, thanks a lot for your comments.
I will create 2 helper scripts that even can be used as actions, one is adding the annotation and the other one will remove the annotation.

I'm already testing the main script :-)
